= `podtime`

== Vision

This is a tiny tool that prints the amount of time left in all the unheard podcasts in my local https://gpodder.github.io/[gPodder] database. The idea is adapted from a discussion about Overcast in https://atp.fm/388[the ATP episode 388] (around 02:15:20).

I remove most of the heard episodes in gPodder and keep only a small percentage of them. Since the whole purpose of the program is to show me how much behind current episodes I am, unheard episodes are considered all the ones which are newer than the oldest unheard episode (including that one) even if they are not marked as new in gPodder:

----
Podcast's episodes sorted by descending published date (newer to older):

Episode #7  // downloaded, new
Episode #6  // downloaded, not new
Episode #5  // downloaded, not new
Episode #4  // downloaded, new
Episode #3  // downloaded, new      // <- this and above are considered unheard
Episode #2  // downloaded, not new  // <- this and below are old
Episode #1  // downloaded, not new
Episode #0  // deleted
----

Here episodes #3–7 are used because #3 is the oldest downloaded and unheard episode.

In the script, there is no way to distinguish the episodes that I've listened to and saved from the episodes that I haven't heard yet.

=== Technical details

The tool is implemented in https://www.haskell.org/[Haskell]. There should be at least some unit tests as applicable.

A quick and dirty proof-of-concept is implemented in shell.

==== `gPodder`

gPodder's default directory is `~/gPodder/` where `Database` is a https://sqlite.org/index.html[SQLite] database with the information about all the added podcasts and episodes.

For a podcast, the tool finds the earliest unheard episode (in the database, `episode.state = 1` (that is https://github.com/gpodder/gpodder/blob/3.10.16/src/gpodder/__init__.py#L155[`DOWNLOADED`]) and `episode.is_new`) and all the newer episodes (by `episode.published`) and extracts their filenames on disk (`episode.download_filename`). The base directory for the podcast is stored in `podcast.download_folder`. This is repeated for every podcast.

To change the gPodder's default directory, you can set the `GPODDER_HOME` environment variable. The tool should support this variable too.

==== MP3 duration

The vast majority of podcasts is distributed as MP3 files, so the tool supports only this format.

The https://unix.stackexchange.com/questions/480375/how-to-find-accumulated-duration-on-several-mp3-with-command-line[basic command] to get the duration is:

----
$ ffprobe -hide_banner -v warning -select_streams a:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 $FILE
[mp3 @ 0x7fb1d8003000] Estimating duration from bitrate, this may be inaccurate
2379.274833
----

Some files are VBR and don't contain the proper information header, so to get the accurate MP3 duration it's necessary to count every MP3 frame in the file. The warning in the command above indicates this. It's possible to use `ffmpeg` to reencode the file into `null` and get the correct duration, but there is https://stackoverflow.com/questions/8933053/check-duration-of-audio-files-on-the-command-line/46493743#46493743[an easier way]:

----
$ sox --info -D $FILE
2382.841995
----

TIP: You can pass multiple filenames to the `sox` command above and it will print the durations of all of them, which should be faster and use less resources than to create a process for each file.

What's left is to sum up all the durations and present the result in a readable time duration format (`HH:MM:SS`).
